### ISSUE TITLE
Doesn't work with multi-line links

### ISSUE THREAD

**Issue by leo** [zeit/hyperlinks#6]
<img width="562" alt="screen shot 2016-08-14 at 10 16 51" src="https://cloud.githubusercontent.com/assets/6170607/17648055/e4fde3e6-6208-11e6-9bcf-6d2d53a8a30c.png">

**Comment by nkzawa** [comment]
This should be fixed on `v0.2.1`.

**Comment by lucasmotta** [comment]
Hey @nkzawa, it's still broken for me on the latest version. See screenshot:

<img width="706" alt="screen shot 2016-11-22 at 11 31 51" src="https://cloud.githubusercontent.com/assets/76673/20522280/59aa2cd0-b0a7-11e6-8d0a-bf8fefb82c4d.png">

**Comment by mattgrosso** [comment]
I am having this issue as well.
MacOS 10.13.1
Hyper 1.4.8 (stable)

Should I post this on #20 or here?

**Comment by leo** [comment]
This package will be deprecated soon! Hyper 2 contains this functionality 😊
